spring.application.name=filing-notification-sender-java

# Actuator Health Check Config
management.endpoints.enabled-by-default=false
management.endpoint.health.enabled=true
management.endpoints.web.base-path=/
management.endpoints.web.path-mapping.health=filing-notification-sender-java/healthcheck
management.endpoint.health.show-details=always

spring.kafka.bootstrap-servers=${BOOTSTRAP_SERVER_URL}

# Kafka Consumer Config
filing-received.consumer.group=${FILING_RECEIVED_CONSUMER_GROUP_NAME}
filing-received.consumer.topic=${FILING_RECEIVED_TOPIC}
#filing-received.consumer.offset=${FILING_RECEIVED_TOPIC_OFFSET}

filing-received-retry.consumer.group=${FILING_RECEIVED_CONSUMER_GROUP_NAME}-filing-retry
filing-received-retry.consumer.topic=${FILING_RECEIVED_TOPIC}-filing-notification-sender-retry
#filing-received-retry.consumer.offset=${FILING_RECEIVED_TOPIC_OFFSET}

filing-processed.consumer.group=${FILING_PROCESSED_CONSUMER_GROUP_NAME}
filing-processed.consumer.topic=${FILING_PROCESSED_TOPIC}
#filing-processed.consumer.offset=${FILING_RECEIVED_TOPIC_OFFSET}

filing-processed-retry.consumer.group=${FILING_PROCESSED_CONSUMER_GROUP_NAME}-retry
filing-processed-retry.consumer.topic=${FILING_PROCESSED_TOPIC}-filing-notification-sender-retry
#filing-processed-retry.consumer.offset=${FILING_RECEIVED_TOPIC_OFFSET}

# Kafka Producer Config
message-send-producer.topic=${MESSAGE_SEND_TOPIC}
log.producer.topic=${LOG_TOPIC}

is.error.consumer=${IS_ERROR_QUEUE_CONSUMER}
max.retry.attempts=${MAXIMUM_RETRY_ATTEMPTS}